# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenV vcontrold to HomA MQTT
version: "1.12.5"
slug: openv-homA
description: Connect a Vito heating system using the HomA MQTT framework
url: "https://github.com/hmueller01/homeassistant-openv-homA"
#image: "ghcr.io/hmueller01/{arch}-addon-openv-homa" # on https://github.com
#image: "hmueller01/{arch}-addon-openv-homa" # on https://hub.docker.com
#image: "hmueller01/homeassistant-addon-openv-homa:{arch}" # on https://hub.docker.com
#image: "hmueller01/homeassistant-addon-openv-homa" # on https://hub.docker.com
image: "alexandreio/{arch}-homeassistant-vcontrol"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  tty: "/dev/ttyUSB0"
  refresh: 60
  device_id: "20CB"
  mqtt_topic: "123456-vito"
  debug: false
  commands:
    - getTempA:FLOAT
    - getTempAtp:FLOAT
    - getTempRaumM2:FLOAT
    - getTempWWist:FLOAT
    - getTempWWsoll:FLOAT
    - getTempKist:FLOAT
    - getTempKsoll:FLOAT
    - getTempVListM2:FLOAT
    - getTempVLsollM2:FLOAT
    - getTempKol:FLOAT
    - getTempStp:FLOAT
    - getTempSpu:FLOAT
    - getTempRaumNorSollM1:FLOAT
    - getTempRaumNorSollM2:FLOAT
    - getTempRaumRedSollM1:FLOAT
    - getTempRaumRedSollM2:FLOAT
    - getBetriebArtM2:STRING
    - getLeistungIst:FLOAT
    - getTempAbgas:FLOAT
    - getBrennerStatus:FLOAT
    - getBrennerStarts:FLOAT
    - getBrennerStunden1:FLOAT
    - getBrennerStunden2:FLOAT
    - getPumpeStatusM1:STRING
    - getPumpeStatusSp:STRING
    - getPumpeStatusZirku:STRING
    - getPumpeStatusM2:STRING
    - getMischerM1:FLOAT
    - getMischerM2:FLOAT
    - getMischerM3:FLOAT
    - getUmschaltventil:STRING
    - getError0:STRING
    - getError1:STRING
    - getError2:STRING
    - getError3:STRING
    - getError4:STRING
    - getError5:STRING
    - getError6:STRING
    - getError7:STRING
    - getError8:STRING
    - getError9:STRING
    - getNeigungM1:FLOAT
    - getNeigungM2:FLOAT
    - getNiveauM1:FLOAT
    - getNiveauM2:FLOAT
    - getSystemTime:STRING
schema:
  tty: "str"
  refresh: "int"
  device_id: "str"
  vcontrol_host: "str?"
  vcontrol_port: "int?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_topic: "str"
  debug: "bool?"
  commands:
    - "str"
usb: true
apparmor: false
ports:
  3002/tcp: null
ports_description:
  3002/tcp: "Vcontrol deamon"
services:
  - mqtt:need
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2
  - /dev/ttyUSB3
map: 
  - type: config
    read_only: False
